# Generated by Django 4.1.4 on 2023-01-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
    ]
