version: '3.8'

services:
  redis:
    image: redis
    env_file:
      - /home/hamza/Desktop/wor/product/product/.env

  db:
    image: postgres
    env_file:
      - /home/hamza/Desktop/wor/product/product/.env
    ports:
      - "5434:5433"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - /home/hamza/Desktop/wor/product/product/.env
    environment:
      DEBUG: 'true'